Release videogames V1.0
DavidEspinoG/mc_videogames_front pull request #43
Opened 2023-07-20 21:31 UTC by DavidEspinoG

## Hello, code reviewer
In this PR we implement all the project requirements: 
- The design follow the layout created by [Murat Korkmaz](https://www.behance.net/muratk)
- We decided to create a web page that let the user reserve a videogame for rent. 
- We are a 5 people team: @sanieni6, @dicodiaz, @DavidEspinoG, @AlejandraKeber and @NicolasAndrehh 
- The user can log in with password and email 
Test admin: 
`email: luis@example.com 
password: password
`
Test user: 
`email: david@example.com 
password: password
`
- Implemented reservation form
- Implemented my reservations view
- Add and delete videogame view, (only available for admin)
- We implemented a details view that shows details of every videogame
- Our web site is fully responsive
- We implemented authentication using devise-jwt on the backend

## Link to backend PR
[Link to backend PR ](https://github.com/sanieni6/mc_videogames_back/pull/24)

2023-07-21 00:13 UTC, mcrd25 requested changes
Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- I really like that you went above the requirements 👍 
- You seem to meet all funcational requirements in general 👍 
- UI is good 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- There is no way to sign up - no sign up route visible from UI or code
- This is subjective but: Don't forget that the application needs to look exactly like design with exception of photos, titles and descriptions. Fonts and sizes seem slightly off.
- [OPTIONAL] c0nsider using the `useCallback` hook to avoid unnecessary re-renders.
*  I am not seeing tests for your Front-End code - this is something we expect to be implemented for the final evaluation. Here are some resources you can use:
   *  https://reactjs.org/docs/testing.html
   * https://jestjs.io/docs/tutorial-react
   * https://www.freecodecamp.org/news/testing-react-hooks/
- I gave some examples but maybe you should consider seeing where else your componenets are a bit bulky and can be cleaned up with the DRY rule

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 00:13 UTC, mcrd25 commented on src/components/navigation.jsx
> +  );
[OPTIONAL]

This componenet is not super long but yo ucan consider abstracting with an array and some sort of looping method. 🙂

2023-07-21 00:13 UTC, mcrd25 commented on src/components/Reservation.jsx
> +        <p className="d-webkit-box clamp-3">{description}</p>
The formatting of reservation details is repeated a few times with slight differences. You could create a small sub-component or a function that formats this data for you to make the code DRY. For example: 

  

```jsx 

const Detail = ({label, value}) => ( 

  <p className="mb-0"> 

    <span className="fw-bold">{label}:</span> 

    {' '} 

    {value} 

  </p> 

); 

``` 

  

And use it in your component: 

  

```jsx 

<Detail label="Starting date" value={formatDate(createdAt)} /> 

<Detail label="Finishing date" value={formatDate(createdAt, days)} /> 

<Detail label="Days" value={days} /> 

<Detail label="Total price" value={formatToCurrency(totalPrice)} /> 

```

2023-07-24 23:07 UTC, Meltrust requested changes
Hi @DavidEspinoG,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Frontend Tests are passing✔️
-  Nice code organization ✔️ 
-  App is working well✔️ 
-  Good readme ✔️ 
-  Beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-07-24 23:07 UTC, Meltrust commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ]  On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project.

Kindly, link to the correct license file that exists in your project.

That way, your app will be well documented 💪

2023-07-24 23:07 UTC, Meltrust commented on README.md
> +<div align="center" id='readme-top'>
- [ ] Congratulations, all your frontend tests are passing:

![image](https://github.com/DavidEspinoG/mc_videogames_front/assets/57421823/b5a0810d-5884-4c88-9e1d-ab64aed641aa)

Now, kindly add a "Tests" section on your readme with instructions about how to run them properly. 👍

2023-07-25 20:56 UTC, merged